# Everyday CLI tools
brew "git"
brew "gh"
brew "wget"
brew "curl"
brew "tree"
brew "jq"
brew "yq"
brew "fzf"
brew "ripgrep"
brew "bat"
brew "eza"
brew "htop"
brew "tmux"
brew "zoxide"
brew "diffutils"
brew "yt-dlp"
brew "ffmpeg"

# Containers, Kubernetes, and infrastructure
brew "docker"
brew "docker-compose"
brew "kubectl"
brew "helm"
brew "k9s"
brew "kind"
brew "ansible"
brew "argocd"
brew "stern"
brew "kubectx"
brew "kustomize"

# Languages and package managers
brew "python"
brew "go"
brew "node"
brew "nvm"
brew "mas"

# Desktop applications
cask "iterm2"
cask "visual-studio-code"
cask "docker-desktop"
cask "rectangle"
